version: '3.8'
services:
  sistema-materias_docker_db:
    container_name: sistema-materias_docker_db
    image: mariadb:10.11
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MARIADB_ROOT_PASSWORD: H26x5!PnL0LE
      MARIADB_DATABASE: sistema_db
      MARIADB_USER: sistema_db_usr
      MARIADB_PASSWORD: H26x5!PnL0LE
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
